version: '3.8'

services:

    simple-web-service:
        image: devopsdockeruh/simple-web-service
        build: .
        command: server
        ports:
            - 8000:8000
        container_name: ex_2.2 